### ISSUE TITLE
Implement plugins manager structure

### ISSUE THREAD

**Issue by shahryarjb** [shahryarjb/mishka-cms#148]
After talking to @pouriya, I have decided to research about `ejabberd` plugins manager solutions. **Then we stop doing all updates out of our issues** and start learning and implementing a basic structure of plugins manager.

> This structure should force developers to work in a prepared template, which is introduced by MishkaCMS core in its documents

---

- [x] Stop the Deadlines
- [x] Send a post about it to Elixir forum
- [x] Create a schema and graph about implementing
- [x] Considering Joomla events → https://github.com/mishka-group/mishka-cms/issues/148#issuecomment-1008177070
- [x] Change version 0.0.2 plans of Projects (Project [0.0.2](https://github.com/mishka-group/mishka-cms/projects/2))
- [x] Register Hook v1
- [x] Start Hook v1
- [x] Restart Hook v1
- [x] Stop Hook v1
- [x] Delete Hook v1
- [x] Unregister Hook v1
- [x] Call `init` of developer's plugin functions, when server is started
- [x] Call  Hook v1
- [x] `ensure_event?`  Hook v1
- [x] Test Hook
- [x] Test state
- [x] Implement plugin system
- [x] mishka-group/mishka_installer#2
- [x] Start creating tests
- [x] Create `db` of plugins
- [x] mishka-group/mishka-cms#168
> It doesn't matter we should duplicate activity of mishka_content because it helps us to delete circle of `deps`
- [x] Identify some predefined behaviors and callbacks
- [x] Add `depends` callback, based on https://github.com/mishka-group/mishka-cms/issues/148#issuecomment-1004047170
- [x] Specify event naming structure
- [x] mishka-group/mishka-cms#163
- [x] mishka-group/mishka-cms#164
- [x] mishka-group/mishka-cms#165
- [x] mishka-group/mishka-cms#155
- [x] Create Genserver Supervisor
- [x] Create Genserver Binding from beginning starting server
- [x] mishka-group/mishka-cms#160
- [x] mishka-group/mishka-cms#154
- [x] mishka-group/mishka-cms#153
- [x] mishka-group/mishka-cms#161
- [x] mishka-group/mishka-cms#166
1. Register and Login sending email
2. Date converter, `Jalaali`
- [x] New features?
1. what we should do about router? (the plugins need to import routers)
2. Decide how to inform admin to update the plugins which have new versions (https://github.com/hexpm/hexpm/issues/1124)
3. Add a better way to remember all the plugin added in Application to restore them.

```elixir
I will update this post , connect this to some pull requests
```

---

### Initial diagram
![mishka-plugin](https://user-images.githubusercontent.com/8413604/147889836-4e190ae1-6fe6-46e1-86f8-6401773e096d.png)

---

### Talks:
1. Start the proposal and the topic raised --> https://youtu.be/FPDxyX4RzZc (Persian)
4. Suggestion to bind dynamic supervisor form starting server --> https://elixirforum.com/t/45419
---

### Refs: 
1. https://github.com/processone/ejabberd/blob/master/src/gen_mod.erl#L89-L92
3. https://hexdocs.pm/plug/Plug.Conn.html
5. https://www.ejabberd.im/
6. [How to add and install deps without stopping phoenix server (hex package)](https://elixirforum.com/t/how-to-add-and-install-deps-without-stopping-phoenix-server-hex-package/44888)
7. [How to create Ecto temporary tables for test a library](https://elixirforum.com/t/how-to-create-ecto-temporary-tables-for-test-a-library/44890)
8. [Need advice to implement custom extension and template installation in an elixir CMS](https://elixirforum.com/t/need-advice-to-implement-custom-extension-and-template-installation-in-an-elixir-cms/44863/)
9. [How to check a macro was called in a module](https://elixirforum.com/t/how-to-check-a-macro-was-called-in-a-module/44674)
10. https://docs.joomla.org/Plugin/Events
11. https://developer.wordpress.org/plugins/hooks/actions/
12. https://elixirforum.com/t/how-to-get-ecto-stream-respond-in-exunit/46138
13. https://elixirforum.com/t/genserver-doesnt-consider-ecto-sandbox/46105
14. https://elixirforum.com/t/dynamicsupervisor-terminate-genserver-state-in-transient-restart-method/45932/2
15. https://elixirforum.com/t/genserver-terminate-strategy-and-re-bind-data/45779
16. https://elixirforum.com/t/how-to-send-sandbox-allow-for-each-dynamic-supervisor-testing/46422/4
17. https://github.com/hexpm/hexpm/issues/1124

**Comment by mojtaba-naseri** [comment]
With this pattern, we need strong documents. Do you have a plan to import new event names for custom sub-system now?

**Comment by shahryarjb** [comment]
@mojtaba-naseri, unfortunately I have no plan for new component or sub-system what developers create, but I added it as a TODO for re-search in first post

**Comment by iArazar** [comment]
If we prepare extra arguments to implement dependencies and priority to load plugins can be helpful, for example:

* Priorities of plugins registered in an event
* Does a plugin need another high-priority output?
* Just load the plugins in order, or we drop them?

**Comment by pouriya** [comment]
In Ejabberd modules there is a callback function `depends` with return value in form of:
```erlang
[{another_module, hard}, {foo_module, soft}]
```
`hard` means this module needs `another_module` to be configured and started and `soft` means this module only calls some utility codes of `foo_module` So we need to install `foo_module` but not to start it.  

And the module manager system makes a direct graph for modules to start them [here](https://github.com/processone/ejabberd/blob/master/src/gen_mod.erl#L547).

**Comment by shahryarjb** [comment]
@pouriya Thank you, it is an excellent idea and solution. This makes developers more organized and also gets more information from a plugin. Infrastructure (plugin system manager) can also be more secure when running a product. I added this guidance to first post's TODO list.

Sincerely yours.

**Comment by shahryarjb** [comment]
@iArazar I will consider high-priority of plugins output

**Comment by shahryarjb** [comment]
@pouriya, Hello again, I have read about your comment below, but I have not understood what is it? I think there is a different keyword in elixir. **Would you mind explaining about this feature?**
> And the module manager system makes a direct graph for modules to start them [here](https://github.com/processone/ejabberd/blob/master/src/gen_mod.erl#L547).

**Comment by pouriya** [comment]
you mean the `digragh` library? it's for dependency detection and prevents circular dependency between plugins

**Comment by shahryarjb** [comment]
Thank you @pouriya, I think ‍‍‍‍`mix` in elixir does this job 🧐 🤭, but I will test it.
> you mean the `digragh` library? It's for dependency detection and prevents circular dependency between plugins.

Thank you again for all your efforts, I am appreciated.

**Comment by shahryarjb** [comment]
In the first phase, about 32 events were selected from **Joomla!**; it is without MishkaCms custom events.
Each event targets a part of the CMS and can be an HTML view or just doing something.


# Updated, some events were deleted

```elixir
  @spec system_events :: [event]
  def system_events do
    [
      # Content
      %Event{name: :on_content_prepare, section: :mishka_content, reference: Ref.OnContentPrepare},
      %Event{name: :on_content_after_title, section: :mishka_content, reference: Ref.OnContentAfterTitle},
      %Event{name: :on_content_before_display, section: :mishka_content, reference: Ref.OnContentBeforeDisplay},
      %Event{name: :on_content_after_display, section: :mishka_content, reference: Ref.OnContentAfterDisplay},
      %Event{name: :on_content_before_save, section: :mishka_content, reference: Ref.OnContentBeforeSave},
      %Event{name: :on_content_after_save, section: :mishka_content, reference: Ref.OnContentAfterSave},
      %Event{name: :on_content_prepare_form, section: :mishka_content, reference: Ref.OnContentPrepareForm},
      %Event{name: :on_content_prepare_data, section: :mishka_content, reference: Ref.OnContentPrepareData},
      %Event{name: :on_content_before_delete, section: :mishka_content, reference: Ref.OnContentBeforeDelete},
      %Event{name: :on_content_after_delete, section: :mishka_content, reference: Ref.OnContentAfterDelete},
      %Event{name: :on_content_change_state, section: :mishka_content, reference: Ref.OnContentChangeState},
      %Event{name: :on_content_search, section: :mishka_content, reference: Ref.OnContentSearch},
      %Event{name: :on_content_search_areas, section: :mishka_content, reference: Ref.OnContentSearchAreas},
      # Captcha
      %Event{name: :on_init, section: :mishka_user, reference: Ref.OnInit},
      %Event{name: :on_display, section: :mishka_user, reference: Ref.OnDisplay},
      %Event{name: :on_check_answer, section: :mishka_user, reference: Ref.OnCheckAnswer},
      %Event{name: :on_privacy_collect_admin_capabilities, section: :mishka_user, reference: Ref.OnPrivacyCollectAdminCapabilities},
      # User
      %Event{name: :on_user_authorisation, section: :mishka_user, reference: Ref.OnUserAuthorisation},
      %Event{name: :on_user_authorisation_failure, section: :mishka_user, reference: Ref.OnUserAuthorisationFailure},
      %Event{name: :on_user_before_save, section: :mishka_user, reference: Ref.OnUserBeforeSave},
      %Event{name: :on_user_after_save, section: :mishka_user, reference: Ref.OnUserAfterSave},
      %Event{name: :on_user_after_delete, section: :mishka_user, reference: Ref.OnUserAfterDelete},
      %Event{name: :on_user_login, section: :mishka_user, reference: Ref.OnUserLogin},
      %Event{name: :on_user_login_failure, section: :mishka_user, reference: Ref.OnUserLoginFailure},
      %Event{name: :on_user_after_login, section: :mishka_user, reference: Ref.OnUserAfterLogin},
      %Event{name: :on_user_after_logout, section: :mishka_user, reference: Ref.OnUserAfterLogout},
      %Event{name: :on_user_after_save_role, section: :mishka_user, reference: Ref.OnUserAfterSaveRole},
      %Event{name: :on_user_after_delete_role, section: :mishka_user, reference: Ref.OnUserAfterDeleteRole}
    ]
  end
```

**Comment by shahryarjb** [comment]
In this time, we tested an event and 2 status of a hook plugin `{:reply, state()} | {:reply, :halt, state()}` 🖤

---

### Update new event:
```elixir
%Event{name: :on_user_after_save_failure, section: :mishka_user, reference: Ref.OnUserAfterSaveFailure}
```

**Comment by shahryarjb** [comment]
We separated [Elixir system plugin manager](https://github.com/mishka-group/mishka_installer) to new Repo

**Comment by shahryarjb** [comment]
Done!
